table Fact_Sales
	lineageTag: 090b0194-d69d-4378-90ea-a1be2ff20226

	column SalesID
		dataType: int64
		formatString: 0
		lineageTag: 8eaeb1a4-36a9-41de-99ed-f509f4c861de
		summarizeBy: count
		sourceColumn: SalesID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 11dd96d9-cced-46e1-84f1-f9006408c4df
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: b2f450f7-f8d1-42fe-a195-59102daf5061
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 69c87c35-a0c7-41a9-a6de-ba3d88978869
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column ChannelKey
		dataType: int64
		formatString: 0
		lineageTag: 50a4e244-79ad-478b-989c-c0d56b4cad2e
		summarizeBy: none
		sourceColumn: ChannelKey

		annotation SummarizationSetBy = Automatic

	column RegionKey
		dataType: int64
		formatString: 0
		lineageTag: 205df280-3c34-4cfc-b16e-b98eec1d9608
		summarizeBy: none
		sourceColumn: RegionKey

		annotation SummarizationSetBy = Automatic

	column SalesVolume
		dataType: int64
		formatString: 0
		lineageTag: 610fdc14-bb3c-4bf6-8378-31a18fd6f6c9
		summarizeBy: sum
		sourceColumn: SalesVolume

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: double
		lineageTag: 9c307eb0-cac5-4f43-97e8-2e6792b84a12
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesValue
		dataType: double
		lineageTag: 5234a6f2-49a8-40cd-b698-04b194658594
		summarizeBy: sum
		sourceColumn: SalesValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Portfolio\github\github projects\Eng.Sameh Bootcamp\jop posts\henkel\Henkel_Market_Intelligence_Dataset_100K.xlsx"), null, true),
				    Fact_Sales_Sheet = Source{[Item="Fact_Sales",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Fact_Sales_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SalesID", Int64.Type}, {"DateKey", Int64.Type}, {"ProductKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"ChannelKey", Int64.Type}, {"RegionKey", Int64.Type}, {"SalesVolume", Int64.Type}, {"UnitCost", type number}, {"SalesValue", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

